// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package Sample

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type Armor struct {
	_tab flatbuffers.Table
}

func GetRootAsArmor(buf []byte, offset flatbuffers.UOffsetT) *Armor {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &Armor{}
	x.Init(buf, n+offset)
	return x
}

func (rcv *Armor) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *Armor) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *Armor) Name() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *Armor) Defense() int16 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.GetInt16(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *Armor) MutateDefense(n int16) bool {
	return rcv._tab.MutateInt16Slot(6, n)
}

func ArmorStart(builder *flatbuffers.Builder) {
	builder.StartObject(2)
}
func ArmorAddName(builder *flatbuffers.Builder, name flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(name), 0)
}
func ArmorAddDefense(builder *flatbuffers.Builder, defense int16) {
	builder.PrependInt16Slot(1, defense, 0)
}
func ArmorEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
